-- Generated by scripts/migrate-to-d1.mjs — do not edit by hand.
-- Re-runnable: existing rows are replaced rather than duplicated.

INSERT OR REPLACE INTO photos (id, src, width, height, alt, caption, captured_at, tags) VALUES ('p001', 'https://picsum.photos/id/1015/1600/2131', 1600, 2131, '河谷与晨雾', '河谷 · 晨雾未散', '2024-04-02', '["landscape","water","quiet"]');
INSERT OR REPLACE INTO photos (id, src, width, height, alt, caption, captured_at, tags) VALUES ('p002', 'https://picsum.photos/id/1043/1600/1067', 1600, 1067, '干燥的荒野植被', '荒野 · 午后', '2024-04-03', '["landscape","texture"]');
INSERT OR REPLACE INTO photos (id, src, width, height, alt, caption, captured_at, tags) VALUES ('p003', 'https://picsum.photos/id/1025/1400/1867', 1400, 1867, '静卧的犬', '静', '2024-05-11', '["portrait","quiet"]');
INSERT OR REPLACE INTO photos (id, src, width, height, alt, caption, captured_at, tags) VALUES ('p004', 'https://picsum.photos/id/1074/1600/1067', 1600, 1067, '林间光影', '林间 · 光落下来', '2024-05-20', '["landscape","light"]');
INSERT OR REPLACE INTO photos (id, src, width, height, alt, caption, captured_at, tags) VALUES ('p005', 'https://picsum.photos/id/1011/1600/2000', 1600, 2000, '海边礁石', '礁石 · 退潮', '2024-06-02', '["seascape","texture"]');
INSERT OR REPLACE INTO photos (id, src, width, height, alt, caption, captured_at, tags) VALUES ('p006', 'https://picsum.photos/id/1039/1600/1067', 1600, 1067, '雪山轮廓', '雪线之上', '2024-06-15', '["landscape","mountain"]');
INSERT OR REPLACE INTO photos (id, src, width, height, alt, caption, captured_at, tags) VALUES ('p007', 'https://picsum.photos/id/1062/1400/1867', 1400, 1867, '空椅子', '空', '2024-07-01', '["still-life","quiet"]');
INSERT OR REPLACE INTO photos (id, src, width, height, alt, caption, captured_at, tags) VALUES ('p008', 'https://picsum.photos/id/1080/1600/1067', 1600, 1067, '老墙与光斑', '墙 · 剥落的时间', '2024-07-19', '["texture","urban"]');
INSERT OR REPLACE INTO photos (id, src, width, height, alt, caption, captured_at, tags) VALUES ('p009', 'https://picsum.photos/id/1069/1600/2131', 1600, 2131, '窗边侧影', '窗', '2024-08-04', '["portrait","light"]');
INSERT OR REPLACE INTO photos (id, src, width, height, alt, caption, captured_at, tags) VALUES ('p010', 'https://picsum.photos/id/1084/1600/1067', 1600, 1067, '湖面倒影', '倒影', '2024-08-22', '["landscape","water","quiet"]');
INSERT OR REPLACE INTO photos (id, src, width, height, alt, caption, captured_at, tags) VALUES ('p011', 'https://picsum.photos/id/1016/1600/1067', 1600, 1067, '沙丘曲线', '沙丘', '2024-09-03', '["landscape","texture"]');
INSERT OR REPLACE INTO photos (id, src, width, height, alt, caption, captured_at, tags) VALUES ('p012', 'https://picsum.photos/id/1002/1600/2131', 1600, 2131, '石阶尽头', '尽头', '2024-09-28', '["urban","quiet"]');
INSERT OR REPLACE INTO photos (id, src, width, height, alt, caption, captured_at, tags) VALUES ('p_jnqpzl67zfhcaojhcq50', 'https://res.cloudinary.com/guwsow6m/image/upload/f_auto,q_auto/v1787709688/jnqpzl67zfhcaojhcq50.jpg', 3169, 3169, 'DSC_2987', NULL, '2026-06-10', '[]');
INSERT OR REPLACE INTO photos (id, src, width, height, alt, caption, captured_at, tags) VALUES ('p_lxstwhd1pnqeyg6zxrto', 'https://res.cloudinary.com/guwsow6m/image/upload/f_auto,q_auto/lxstwhd1pnqeyg6zxrto.jpg', 2254, 2176, 'lxstwhd1pnqeyg6zxrto', NULL, '2026-06-10', '[]');
INSERT OR REPLACE INTO photos (id, src, width, height, alt, caption, captured_at, tags) VALUES ('p_exbeg4h2c82fyx91l6i8', 'https://res.cloudinary.com/guwsow6m/image/upload/f_auto,q_auto/exbeg4h2c82fyx91l6i8.jpg', 4016, 4016, 'exbeg4h2c82fyx91l6i8', NULL, '2026-06-10', '[]');
INSERT OR REPLACE INTO photos (id, src, width, height, alt, caption, captured_at, tags) VALUES ('p_g5vtlvsfkns3ozsmpotj', 'https://res.cloudinary.com/guwsow6m/image/upload/f_auto,q_auto/v1787709749/g5vtlvsfkns3ozsmpotj.jpg', 4016, 4016, 'DSC_0110', NULL, '2026-06-10', '[]');

INSERT OR REPLACE INTO series (slug, title, subtitle, description, layout, cover, published, flow_direction, accent_color, background_mode, custom_background, frame_style, canvas_ratio, sort_index, updated_at) VALUES ('Grassland', 'Grassland', '在草原', NULL, 'flow', 'p_jnqpzl67zfhcaojhcq50', 1, 'horizontal', '#6e8072', 'accent', NULL, 'rounded', '3 / 2', 0, '2026-08-27T07:35:42.675Z');
INSERT OR REPLACE INTO series_photos (series_slug, photo_id, position, x, y, w, h, z) VALUES ('Grassland', 'p_jnqpzl67zfhcaojhcq50', 0, NULL, NULL, NULL, NULL, NULL);
INSERT OR REPLACE INTO series_photos (series_slug, photo_id, position, x, y, w, h, z) VALUES ('Grassland', 'p_lxstwhd1pnqeyg6zxrto', 1, NULL, NULL, NULL, NULL, NULL);
INSERT OR REPLACE INTO series_photos (series_slug, photo_id, position, x, y, w, h, z) VALUES ('Grassland', 'p_exbeg4h2c82fyx91l6i8', 2, NULL, NULL, NULL, NULL, NULL);
INSERT OR REPLACE INTO series_photos (series_slug, photo_id, position, x, y, w, h, z) VALUES ('Grassland', 'p_g5vtlvsfkns3ozsmpotj', 3, NULL, NULL, NULL, NULL, NULL);

