/**
 * Turns the existing photos.json / series.json into SQL for D1.
 *
 * Writes db/seed.sql rather than talking to the database directly, so the same
 * file can be applied locally (`--local`) and to the real database, and so the
 * statements can be read before anything is executed.
 *
 *   node scripts/migrate-to-d1.mjs
 */
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";

const root = new URL("../", import.meta.url);
const photos = JSON.parse(readFileSync(new URL("src/data/photos.json", root), "utf8"));
const series = JSON.parse(readFileSync(new URL("src/data/series.json", root), "utf8"));

const q = (v) => {
  if (v === undefined || v === null || v === "") return "NULL";
  return "'" + String(v).replace(/'/g, "''") + "'";
};
const num = (v) => (v === undefined || v === null || Number.isNaN(Number(v)) ? "NULL" : Number(v));

const lines = [
  "-- Generated by scripts/migrate-to-d1.mjs — do not edit by hand.",
  "-- Re-runnable: existing rows are replaced rather than duplicated.",
  "",
];

for (const p of photos) {
  lines.push(
    `INSERT OR REPLACE INTO photos (id, src, width, height, alt, caption, captured_at, tags) VALUES (` +
      [
        q(p.id),
        q(p.src),
        num(p.width),
        num(p.height),
        q(p.alt ?? ""),
        q(p.caption ?? ""),
        q(p.capturedAt),
        q(JSON.stringify(p.tags ?? [])),
      ].join(", ") +
      ");"
  );
}

lines.push("");

series.forEach((s, index) => {
  lines.push(
    `INSERT OR REPLACE INTO series (slug, title, subtitle, description, layout, cover, published, ` +
      `flow_direction, accent_color, background_mode, custom_background, frame_style, canvas_ratio, ` +
      `sort_index, updated_at) VALUES (` +
      [
        q(s.slug),
        q(s.title),
        q(s.subtitle ?? ""),
        q(s.description ?? ""),
        q(s.layout ?? "grid"),
        q(s.cover),
        s.published === false ? 0 : 1,
        q(s.flowDirection),
        q(s.accentColor),
        q(s.backgroundMode ?? "site"),
        q(s.customBackground),
        q(s.frameStyle ?? "square"),
        q(s.canvasRatio ?? "3 / 2"),
        index,
        q(s.updatedAt ?? new Date().toISOString()),
      ].join(", ") +
      ");"
  );

  // Membership rows carry the curated order, plus freeform coordinates when present.
  const frames = new Map((s.frames ?? []).map((f) => [f.id, f]));
  (s.photoIds ?? []).forEach((photoId, position) => {
    const f = frames.get(photoId);
    lines.push(
      `INSERT OR REPLACE INTO series_photos (series_slug, photo_id, position, x, y, w, h, z) VALUES (` +
        [q(s.slug), q(photoId), position, num(f?.x), num(f?.y), num(f?.w), num(f?.h), num(f?.z)].join(", ") +
        ");"
    );
  });
  lines.push("");
});

const out = fileURLToPath(new URL("db/seed.sql", root));
writeFileSync(out, lines.join("\n") + "\n");

const memberships = series.reduce((n, s) => n + (s.photoIds?.length ?? 0), 0);
console.log(`wrote ${out}`);
console.log(`  photos:      ${photos.length}`);
console.log(`  series:      ${series.length}`);
console.log(`  memberships: ${memberships}`);
